export const components = {
  advertising: 'PROPAGANDA',
  customChannel: 'Personalizar Canal',
  channelIcon: 'Icone do canal',
  channelBanner: 'Banner do canal',
  channelName: 'Nome do canal',
  channelDescription: 'Descrição do canal',
  send: 'Enviar',
  cancel: 'Cancelar',
  makeLogin: 'Fazer Login',
  register: 'Registre-se',
  email: 'E-mail',
  password: 'Senha',
  confPassword: 'Confirmação de senha',
  selectEditForm: 'Selecione o formulário de edição',
  editBannerAndIconFromChannel: 'Editar banner e icone do canal',
  editNameAndDescriptionFromChannel: 'Edite nome e descrição do canal',
  managerVideos: 'Gerenciar Videos',
  search: 'Pesquisar',
  channel: 'Canal', 
  leave: 'Sair',
  comments: 'Comentários',
  start: 'Inicio',
  explore: 'Explorar',
  shorts: 'Shorts',
  subscribes: 'Inscritos',
  library: 'Biblioteca',
  historic: 'Histórico',
  subscribed: 'Inscrito',
  signUp: 'Inscreva-se',
}